apiVersion: batch/v1
kind: Job
metadata:
  name: FIXME
  namespace: FIXME
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - command:
        - bash
        - -c
        - exit 1
        image: non-existing-image
        name: ubuntu
      restartPolicy: OnFailure
      imagePullPolicy: Always
