apiVersion: batch/v1
kind: Job
metadata:
  name: FIXME
  namespace: FIXME
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - command:
        - bash
        - -c
        - exit 1
        image: ubuntu:22.04
        name: ubuntu
      restartPolicy: Never
